"""add_ngrok_url_to_youtube_channels

Revision ID: a64ee9cbc7ca
Revises: 4b5c6d7e8f9a
Create Date: 2026-05-29 20:33:40.004982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a64ee9cbc7ca'
down_revision: Union[str, Sequence[str], None] = '4b5c6d7e8f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('channels_url_key'), 'channels', type_='unique')
    op.drop_index(op.f('ix_channels_url'), table_name='channels')
    op.create_index(op.f('ix_channels_url'), 'channels', ['url'], unique=True)
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_constraint(op.f('video_links_url_key'), 'video_links', type_='unique')
    op.drop_index(op.f('ix_video_links_url'), table_name='video_links')
    op.create_index(op.f('ix_video_links_url'), 'video_links', ['url'], unique=True)
    op.create_index(op.f('ix_video_links_id'), 'video_links', ['id'], unique=False)
    op.drop_constraint(op.f('video_links_channel_id_fkey'), 'video_links', type_='foreignkey')
    op.create_foreign_key(None, 'video_links', 'channels', ['channel_id'], ['id'])
    op.add_column('youtube_channels', sa.Column('ngrok_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_channels', 'ngrok_url')
    op.drop_constraint(None, 'video_links', type_='foreignkey')
    op.create_foreign_key(op.f('video_links_channel_id_fkey'), 'video_links', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_video_links_id'), table_name='video_links')
    op.drop_index(op.f('ix_video_links_url'), table_name='video_links')
    op.create_index(op.f('ix_video_links_url'), 'video_links', ['url'], unique=False)
    op.create_unique_constraint(op.f('video_links_url_key'), 'video_links', ['url'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_url'), table_name='channels')
    op.create_index(op.f('ix_channels_url'), 'channels', ['url'], unique=False)
    op.create_unique_constraint(op.f('channels_url_key'), 'channels', ['url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
